[project]
name = "wake-whisper-continuous"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "duckdb>=1.3.1",
    "loguru>=0.7.3",
    "numpy>=2.0,<2.3",
    "pvporcupine>=3.0.5",
    "pvrecorder>=1.2.7",
    "pyaudio>=0.2.14",
]
