[project]
name = "whisper-sandbox"
version = "0.1.0"
description = "OpenAI Whisper音声認識エンジンの検証環境"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openai-whisper>=20240930",
    "pyaudio>=0.2.14",
]

[tool.uv]
dev-dependencies = []
